# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/SignZeroExtend.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/RegisterFile.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/pcAdd.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/PC.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/InstructionCut.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/InsMEM.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/DataMEM.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/ControlUnit.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/ALU.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/SingleCycleCPUBasys.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/Debounce.v
  C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/sources_1/new/showCPU.v
}
read_xdc C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/constrs_1/new/cpu.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/ECOP-16340158-02/code/CPUBasys_SINGLE/CPUBasys_SINGLE.srcs/constrs_1/new/cpu.xdc]

synth_design -top showCPU -part xc7a35tcpg236-1
write_checkpoint -noxdef showCPU.dcp
catch { report_utilization -file showCPU_utilization_synth.rpt -pb showCPU_utilization_synth.pb }
